services:
  vpn-panel:
    image: ghcr.io/rblashchuk/vpn-panel:latest
    container_name: vpn-panel

    restart: unless-stopped

    ports:
      - "127.0.0.1:9000:9000"

    volumes:
      - vpn-panel-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      VPN_SOURCE: docker
      VPN_ENDPOINTS: "awg:amnezia-awg2:awg,wireguard:amnezia-wireguard:wg"
      VPN_PANEL_LISTEN: 0.0.0.0:9000

volumes:
  vpn-panel-data:
